### PR TITLE
Mission update - Battle of the Bulges

### PR DESCRIPTION
**Pull request by TheLocalPub**

### CODE REVIEW

**Comment by TheLocalPub** [comment]
Fixed:
- Capzones being captured by the wrong teams resulting in mission ending very early.
- Missing no mans land markers in middle of the AO.
- Missing splash png image

Added:
- System to regain 10 tickets by recapping/gaining majority back of the capzone that takes your team's tickets if enemy team has a majority within it.

**Review by Til-Weimann — CHANGES_REQUESTED** [review]
The condition of RedTicketAdd / BlueTicketAdd is an OperatorTerm (base version of all operations, not intended for use in mission), instead of a ConjunctionTerm.

**Comment by TheLocalPub** [comment]
Done

**Comment by Til-Weimann** [comment]
Not done, they're still OperatorTerms
image

**Review by Til-Weimann — APPROVED** [review]

**Pull request merged**
